on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DockerHub_USER }}
          password: ${{ secrets.DockerHub_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Docker Compose version
        run: docker compose version

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker compose run --rm app sh -c "flake8 --verbose"
